name: FakeInstagram
options:
  bundleIdPrefix: kimiaki.FakeInstagram
  deploymentTarget: "13.0"
  groupSortPosition: top
  minimumXcodeGenVersion: 2.15.0
  carthageExecutablePath: mint run Carthage/Carthage carthage
configs:
  DebugDevelopment: debug
  DebugProduction: debug
  ReleaseDevelopment: release
  ReleaseProduction: release
settings:
  base:
    MARKETING_VERSION: 1.0.0
    BUILD_VERSION: 1
    OTHER_LDFLAGS: $(OTHER_LDFLAGS) -ObjC
targets:
  Component:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: Component
    dependencies:
      - carthage: Nuke
  FakeInstagram:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: FakeInstagram
    dependencies:
      - target: Component
    preBuildScripts:
      - name: "[SwiftLint] Run Script"
        script: "make swiftlint"
      - name: "[SwiftFormat] Run Script"
        script: "make swiftformat-diff"
